name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sort and commit repos
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          sh sort.sh
