name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sort and commit repos
        run: |
          sh sort.sh
          git add repos-*
          git commit -m "Sort repos"
          git push
