name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sort and commit repos
        run: |
          sh sort.sh
          if git diff --quiet repos-*; then
              git config user.name "GitHub Actions Bot"
              git config user.email "<>"
              git add repos-*
              git commit -m "Sort repos"
              git push
          fi
